CREATE TABLE quests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(255) UNIQUE,
    description VARCHAR(255),
    address     VARCHAR(255),
    phone       VARCHAR(20)
);
