CREATE TABLE bookings
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id  VARCHAR(255) NOT NULL,
    quest_id BIGINT       NOT NULL,
    date     DATE         NOT NULL,
    time     TIME         NOT NULL,

    CONSTRAINT uq_booking UNIQUE (quest_id, date, time),
    CONSTRAINT fk_quest FOREIGN KEY (quest_id) REFERENCES quests (id)
);
