cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

app:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    endpoint: http://minio:9000
    path-style-access: true

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
