spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB_DATABASE}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB_DATABASE}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration

booking:
  available-slots:
    - "10:00"
    - "11:00"
    - "12:00"
    - "13:00"
    - "14:00"
    - "15:00"
    - "16:00"
    - "17:00"
    - "18:00"
    - "19:00"
    - "20:00"
